/**
 * `dataExports/{autoId}`: one append-only row per CSV the site generates.
 *
 * Every export route writes a row here IMMEDIATELY BEFORE it streams the file
 * back, and refuses the export if that write fails (see {@link logExport},
 * which throws rather than swallowing). The register, the roster, the
 * applications table and the membership list are all lists of named people;
 * once a file leaves the platform nothing can follow it, so the one control
 * left is a durable record of who asked for it, what it covered and how many
 * people were in it.
 *
 * WHAT THIS LOG DOES NOT CLAIM. It records DOWNLOADS THE SITE GENERATED, not
 * every way data leaves. A reviewer's queue already renders the whole
 * applications payload in their browser, so copy and paste is outside this
 * log by construction, and the privacy policy says "downloads generated by
 * the site are recorded" for exactly that reason. Do not let a later PR
 * upgrade that sentence to "every export is logged".
 *
 * APPEND-ONLY, AND SHUT TO EVERY CLIENT INCLUDING ADMINS. The `courseAudit`
 * and `courseDeletions` posture verbatim: an audit its own actor can amend is
 * not an audit, and the actor here is usually an admin. Rules are
 * `allow read, write: if false` in an EXPLICIT match block, so a later
 * wildcard cannot open the collection by accident; the admin Exports tab
 * reads it through GET /api/admin/deliverability/exports on the Admin SDK,
 * the same shape the deliverability send log already uses.
 *
 * RETAINED BY BOTH CASCADES, ON PURPOSE. Neither `deleteAccountCascade` nor
 * the run/course DESTROY cascade touches this collection, and that is a
 * decision rather than an oversight:
 *
 *  - a row names the ACTOR of a staff action. Erasing the record of who
 *    exported a cohort's roster because that committee member later deleted
 *    their own account would destroy the only evidence the export ever
 *    happened. `impersonations`, `courseDeletions` and `courseAudit` are
 *    retained on the same reasoning;
 *  - a row holds NO member content: a kind, an actor, a scope of ids, a row
 *    count, a filename and a time. Nobody's answers, marks or notes are here,
 *    so retaining it does not retain anything about the people who were in
 *    the file;
 *  - destroying a run destroys the things an export described, but not the
 *    fact that somebody took a copy of them first. That fact is the point.
 *
 * tests/data-exports.test.mjs pins both halves of that posture against the
 * two cascade sources, so a future PR that quietly adds a drain goes red.
 */

import { FieldValue, type Firestore } from "firebase-admin/firestore";

export const DATA_EXPORTS_COLLECTION = "dataExports";

/**
 * What was exported. One kind per export route; a kind earns its place when
 * somebody would go looking for it by name.
 */
export type DataExportKind =
  /** A group's attendance register for one run, marks included. */
  | "register"
  /** The people enrolled on a run or a group, with their contact details. */
  | "roster"
  /** An admission round's applications and decisions. */
  | "applications"
  /** A membership period's people and tiers. */
  | "membership"
  /** Attendance rolled up per person rather than per session. */
  | "attendance-summary";

export const DATA_EXPORT_KINDS: DataExportKind[] = [
  "register",
  "roster",
  "applications",
  "membership",
  "attendance-summary",
];

/** The label for a kind this build has never heard of. */
export const UNKNOWN_DATA_EXPORT_LABEL = "Unrecognised export";

export const DATA_EXPORT_KIND_LABEL: Record<DataExportKind, string> = {
  register: "Attendance register",
  roster: "Cohort roster",
  applications: "Applications",
  membership: "Membership list",
  "attendance-summary": "Attendance summary",
};

export function isDataExportKind(kind: unknown): kind is DataExportKind {
  return (
    typeof kind === "string" && DATA_EXPORT_KINDS.includes(kind as DataExportKind)
  );
}

/**
 * The label for one row's `kind`, INCLUDING a kind this build predates.
 * Always render through this: a rolled-back deploy, or a newer route writing
 * a kind this bundle has never seen, must not make a row claim to be a
 * different export than it was.
 */
export function dataExportKindLabel(kind: DataExportKind | string): string {
  return isDataExportKind(kind)
    ? DATA_EXPORT_KIND_LABEL[kind]
    : UNKNOWN_DATA_EXPORT_LABEL;
}

export const DATA_EXPORT_LIMITS = {
  actorName: 120,
  filename: 200,
} as const;

/**
 * What the export covered, in ids. Every key is OPTIONAL and an absent key is
 * written ABSENT, never `undefined` (Firestore refuses undefined) and never
 * `null` (a stored null reads back as "there was a scope and it was empty").
 */
export type DataExportScope = {
  runId?: string;
  groupId?: string;
  roundId?: string;
  periodId?: string;
};

const SCOPE_KEYS: (keyof DataExportScope)[] = [
  "runId",
  "groupId",
  "roundId",
  "periodId",
];

/** What a route hands {@link logExport}. `at` is stamped server-side. */
export type DataExportEntry = {
  kind: DataExportKind;
  actorUid: string;
  actorName: string;
  scope: DataExportScope;
  /** People in the file, not bytes. The number a DPO would ask for first. */
  rowCount: number;
  /** The name the browser saved it as, so a file on a laptop can be traced. */
  filename: string;
};

export type DataExportDoc = {
  /** Firestore auto-id. Rows are never addressed individually. */
  id: string;
  /** Kept VERBATIM even when unrecognised. Read `kindKnown` before branching. */
  kind: DataExportKind | string;
  kindKnown: boolean;
  actorUid: string;
  actorName: string;
  scope: DataExportScope;
  rowCount: number;
  filename: string;
  at: Date | null;
  /**
   * Whether the export was taken inside an admin "view as" session.
   *
   * Every export route calls `assertNotImpersonating()` before it does
   * anything else, so in practice this is `false` on every row. It is stored
   * anyway, and read honestly: the marker the guard reads is an httpOnly
   * cookie, so an admin who deliberately clears it in devtools defeats the
   * guard, and the row would then be written by the same request that should
   * have been refused. Treat `false` as "this request presented no view-as
   * marker", which is what it means, rather than as proof of who was at the
   * keyboard.
   */
  viaImpersonation: boolean;
};

type Raw = Record<string, unknown>;

function tsToDate(v: unknown): Date | null {
  if (!v) return null;
  if (v instanceof Date) return v;
  const obj = v as { toDate?: () => Date };
  return typeof obj?.toDate === "function" ? obj.toDate() : null;
}

function str(v: unknown, max: number): string {
  return typeof v === "string" ? v.slice(0, max) : "";
}

function count(v: unknown): number {
  return typeof v === "number" && Number.isFinite(v) ? Math.max(0, Math.trunc(v)) : 0;
}

/**
 * Drop every absent or non-string key, so the written document carries only
 * the ids that really scoped the export. Undefined never reaches Firestore
 * and an unset scope is `{}`, not a map of nulls.
 */
export function compactScope(scope: DataExportScope | undefined): DataExportScope {
  const out: DataExportScope = {};
  if (!scope) return out;
  for (const key of SCOPE_KEYS) {
    const value = scope[key];
    if (typeof value === "string" && value !== "") out[key] = value;
  }
  return out;
}

export function normalizeDataExport(id: string, data: Raw): DataExportDoc {
  const rawKind = typeof data.kind === "string" ? data.kind : "";
  return {
    id,
    kind: rawKind,
    kindKnown: isDataExportKind(rawKind),
    actorUid: typeof data.actorUid === "string" ? data.actorUid : "",
    actorName: str(data.actorName, DATA_EXPORT_LIMITS.actorName),
    scope: compactScope((data.scope ?? {}) as DataExportScope),
    rowCount: count(data.rowCount),
    filename: str(data.filename, DATA_EXPORT_LIMITS.filename),
    at: tsToDate(data.at),
    viaImpersonation: data.viaImpersonation === true,
  };
}

/**
 * Append one row, and THROW if it cannot be written.
 *
 * The throw is the contract, not a detail: a route calls this before it
 * streams, so a failed log write must refuse the export rather than hand over
 * an unlogged file. Call it inside the route's own try/catch and return a 500;
 * never `void logExport(...)`, and never catch-and-continue.
 *
 * `viaImpersonation` is accepted rather than assumed, so a row records what
 * the request itself presented. Every export route calls
 * `assertNotImpersonating()` before reaching here, so every row today is
 * written with `false`.
 */
export async function logExport(
  db: Firestore,
  entry: DataExportEntry,
  { viaImpersonation = false }: { viaImpersonation?: boolean } = {},
): Promise<string> {
  const ref = await db.collection(DATA_EXPORTS_COLLECTION).add({
    kind: entry.kind,
    actorUid: entry.actorUid,
    actorName: str(entry.actorName, DATA_EXPORT_LIMITS.actorName),
    scope: compactScope(entry.scope),
    rowCount: count(entry.rowCount),
    filename: str(entry.filename, DATA_EXPORT_LIMITS.filename),
    at: FieldValue.serverTimestamp(),
    viaImpersonation,
  });
  return ref.id;
}
